### ISSUE TITLE
Add support for keyed service with multiple attributes

### ISSUE THREAD

**Issue by nuzolx** [devlooped/DependencyInjection.Attributed#108]
Hi,

I'd like to be able to specify the attribute several times in the case of keyed service.
Is this possible?
At the moment, error ‘CS0579’ is being thrown. 

```csharp
public interface INotificationService
{
    string Notify(string message);
}

[Service<string>("sms")]
public class SmsNotificationService : INotificationService
{
    public string Notify(string message) => $"[SMS] {message}";
}

[Service<string>("email")]
[Service<string>("default")]
public class EmailNotificationService : INotificationService
{
    public string Notify(string message) => $"[Email] {message}";
}
```

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
This sounds definitely useful. It would involve detecting multiple usages when not using the keyed overload (since that would still be unnecessary), but otherwise, I think it would be a good addition.

Would you care for funding it? 🙏
