### ISSUE TITLE
Library does not work on MAUI

### ISSUE THREAD

**Issue by dlandi** [devlooped/DependencyInjection.Attributed#13]
## Describe the Bug
Because of the peculiarity of MAUI data-binding, normal dependency inject syntax will not work, and we have to use a ServiceProvider "shim" which may be part of the problem.

## Steps to Reproduce
I've provided a video
(https://youtu.be/CKxHnH2Szc4)

**Comment by kzu** [comment]
You haven't called the generated `builder.Services.AddServices();` to register the discovered services, which is documented in the readme.

**Comment by dlandi** [comment]
Confirmed! I missed that. Thanks! Very helpful lib.

**Comment by kzu** [comment]
Shipping an update now that will generate a build warning when this exact same scenario happens :). Should make it easier to fall in the pit of success
